FROM node:14.16.0

WORKDIR /usr/src/app

COPY package.json .

RUN npm install glob rimraf
RUN npm install
RUN npm install argon2 --build-from-source
RUN npm i @nestjs/cli -g

COPY . .

RUN nest build auth

CMD ["nest", "start", "auth"]