version: '3.8'

services:
  wordle-api:
    container_name: wordle
    build:
      context: .
      dockerfile: Dockerfile.wordle
      args:
        APP: wordle
    image: node:14-alpine
    depends_on:
      - wordle-db
      - redis
    networks:
      - wordle
      - redis
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=${APP_PORT}
      - WORDLE_DB_HOST=${WORDLE_DB_HOST}
      - WORDLE_DB_PORT=${WORDLE_DB_PORT}
      - WORDLE_DB_USER=${WORDLE_DB_USER}
      - WORDLE_DB_PASSWORD=${WORDLE_DB_PASSWORD}
      - WORDLE_DB_NAME=${WORDLE_DB_NAME}
      - APP_REDIS=${APP_REDIS}
    ports:
      - ${APP_PORT}:${APP_PORT}
  wordle-auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    image: node:14-alpine
    depends_on:
      - auth-db
      - redis
    networks:
      - wordle_auth
      - redis
    environment:
      - NODE_ENV=${NODE_ENV}
      - AUTH_PORT=${AUTH_PORT}
      - AUTH_DB_HOST=${AUTH_DB_HOST}
      - AUTH_DB_PORT=${AUTH_DB_PORT}
      - AUTH_DB_USER=${AUTH_DB_USER}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - AUTH_DB_NAME=${AUTH_DB_NAME}
      - APP_REDIS=${APP_REDIS}
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  wordle-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - wordle
  auth-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    networks:
      - wordle_auth
  redis:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    networks:
      - redis
networks:
  wordle_auth:
    driver: bridge
  wordle:
    driver: bridge
  redis:
    driver: bridge
